### ISSUE TITLE
Files in output are in random order

### ISSUE THREAD

**Issue by mattiadg** [rwth-i6/fairseq-automos#1]
Hi, thank you for your work to make this more easily usable for us.

I noticed some annoying issues with the way the output is presented.

The outputs files with their scores, in the output file, are not in the same order as in the input file.

The list is loaded with shuffling enabled https://github.com/rwth-i6/fairseq-automos/blob/main/predict.py#L77
and then the order is anyway decided by the result of a `dict.items()` call https://github.com/rwth-i6/fairseq-automos/blob/main/predict.py#L100.

Then, not totally related but still about printing results, some logs are in stderr https://github.com/rwth-i6/fairseq-automos/blob/main/predict.py#L75 and the overall mean in stdout https://github.com/rwth-i6/fairseq-automos/blob/main/predict.py#L95, so there is no trace of it in the output file

**Comment by JackTemaki** [comment]
solved via #4
